[package]
name = "wc3-casc-export"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
casclib = { git = "https://github.com/wc3tools/casclib-rs.git" }
log = "0.4.8"
env_logger = "0.7.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
pbr = "1"

wc3-txt = { path = "../../crates/wc3-txt" }
wc3-image-conv = { path = "../../crates/wc3-image-conv" }